/**
 * Generates the animated README artwork in `.github/assets` straight from
 * `@trinqa/tokens`. Nothing here invents a colour, a type size, a radius or a
 * duration: every value below is read from the design system, so regenerating
 * after a token change keeps the artwork honest.
 *
 *   pnpm assets:readme
 *
 * Geometry is authored in token units and the SVG is presented at 2x, which is
 * why a 38pt wordmark reads as a banner headline without leaving the type scale.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  chartTokens,
  colors,
  motion,
  primitiveOpacity,
  primitiveSpace,
  primitiveType,
  radius,
  semanticColor,
  space,
  typeRole,
  typeWeightRn,
  walletColors,
} from '../packages/tokens/src/index';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../.github/assets');

/** The only font the product loads. */
const FAMILY = `${primitiveType.family}, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif`;

const weight = (role: keyof typeof typeRole) => typeWeightRn[typeRole[role].weight];
const size = (role: keyof typeof typeRole) => typeRole[role].size;

/** Ambient loops are multiples of the product's processing beat (1400ms). */
const BEAT = motion.duration.flowProcessing;
const ms = (beats: number) => `${(BEAT * beats) / 1000}s`;

type Theme = {
  name: 'light' | 'dark';
  bodyStart: string;
  bodyEnd: string;
  stroke: string;
  text: string;
  textMuted: string;
  mark: string;
  chip: string;
  track: string;
  accent: string;
  accentAlt: string;
  glow: string;
};

/** Light = the product's own surfaces. Dark = the wallet surface family. */
const THEMES: Theme[] = [
  {
    name: 'light',
    bodyStart: semanticColor.surface.primary,
    bodyEnd: semanticColor.surface.splash,
    stroke: semanticColor.border.subtle,
    text: semanticColor.text.primary,
    textMuted: semanticColor.text.secondary,
    mark: semanticColor.text.primary,
    chip: semanticColor.surface.primary,
    track: semanticColor.surface.layer,
    accent: colors.action,
    accentAlt: colors.actionPrimaryDarker,
    glow: chartTokens.areaFill,
  },
  {
    name: 'dark',
    bodyStart: walletColors.bodyStart,
    bodyEnd: walletColors.bodyEnd,
    stroke: walletColors.bodyStroke,
    text: walletColors.textPrimary,
    textMuted: walletColors.silver100,
    mark: walletColors.textPrimary,
    chip: walletColors.pocket0,
    track: walletColors.pocketEdge,
    accent: colors.action,
    accentAlt: walletColors.gaugeStart,
    glow: chartTokens.areaFill,
  },
];

const MARK_RADIUS = 31;
/** Offsets taken from the brand mark: the two halves sit 0.26r apart and 0.74r down. */
const MARK_GAP = space[8];
const MARK_DROP = 23;

const mark = (cx: number, cy: number, fill: string) => {
  const leftFlat = cx - MARK_GAP / 2;
  const rightFlat = cx + MARK_GAP / 2;
  const top = cy - MARK_DROP / 2;
  return `
    <g fill="${fill}" stroke="${fill}" stroke-width="${space[4]}" stroke-linejoin="round">
      <path class="halfL" d="M${leftFlat} ${top - MARK_RADIUS} A${MARK_RADIUS} ${MARK_RADIUS} 0 0 0 ${leftFlat} ${top + MARK_RADIUS} Z"/>
      <path class="halfR" d="M${rightFlat} ${top + MARK_DROP - MARK_RADIUS} A${MARK_RADIUS} ${MARK_RADIUS} 0 0 1 ${rightFlat} ${top + MARK_DROP + MARK_RADIUS} Z"/>
    </g>`;
};

const chip = (
  x: number,
  y: number,
  w: number,
  label: string,
  t: Theme,
  highlight?: string,
) => `
      <g>
        <rect x="${x}" y="${y}" width="${w}" height="${primitiveSpace[24]}" rx="${radius.pill}" fill="${t.chip}" stroke="${t.stroke}"/>
        ${highlight ? `<rect class="hl ${highlight}" x="${x}" y="${y}" width="${w}" height="${primitiveSpace[24]}" rx="${radius.pill}" fill="none" stroke="${t.accent}"/>` : ''}
        <text x="${x + w / 2}" y="${y + 15}" fill="${t.text}" text-anchor="middle">${label}</text>
      </g>`;

function banner(t: Theme): string {
  const markX = 88;
  const markY = 100;
  const textX = 150;
  const chipW = 76;
  const chipGap = space[12];
  const chips = ['Stellar', 'Soroban', 'SEP-6/10/38', 'DeFindex', 'Soroswap'];

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 200" width="1280" height="400"
     role="img" aria-label="Trinqa — self-driving portfolio">
  <title>Trinqa — self-driving portfolio</title>
  <desc>Generated by scripts/build-readme-assets.ts from @trinqa/tokens (${t.name} surface).</desc>
  <defs>
    <linearGradient id="body" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${t.bodyStart}"/><stop offset="100%" stop-color="${t.bodyEnd}"/>
    </linearGradient>
    <radialGradient id="glow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="${t.accent}" stop-opacity="${primitiveOpacity.dividerLine}"/>
      <stop offset="60%" stop-color="${t.accent}" stop-opacity="${primitiveOpacity.actionHighlight}"/>
      <stop offset="100%" stop-color="${t.accent}" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="shine" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="${t.accent}" stop-opacity="0"/>
      <stop offset="45%" stop-color="${t.accent}"/>
      <stop offset="55%" stop-color="${t.accentAlt}"/>
      <stop offset="100%" stop-color="${t.accentAlt}" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="rail" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="${t.accent}" stop-opacity="0"/>
      <stop offset="25%" stop-color="${t.accent}"/>
      <stop offset="75%" stop-color="${t.accentAlt}"/>
      <stop offset="100%" stop-color="${t.accentAlt}" stop-opacity="0"/>
    </linearGradient>
    <clipPath id="bodyclip"><rect x="${space[8]}" y="${space[8]}" width="624" height="184" rx="${radius.xl}"/></clipPath>
    <mask id="wordmask">
      <rect width="640" height="200" fill="black"/>
      <text x="${textX}" y="88" font-family="${FAMILY}" font-size="${primitiveType.sizes[38]}"
            font-weight="${typeWeightRn.bold}" letter-spacing="${primitiveType.tracking.walletBalance}" fill="white">Trinqa</text>
    </mask>
    <style>
      .halfL { animation: driftL ${ms(4)} cubic-bezier(.45,0,.2,1) infinite; }
      .halfR { animation: driftR ${ms(4)} cubic-bezier(.45,0,.2,1) infinite; }
      @keyframes driftL { 0%,100% { transform: translate(0,0) } 50% { transform: translate(-${space[4]}px,-3px) } }
      @keyframes driftR { 0%,100% { transform: translate(0,0) } 50% { transform: translate(${space[4]}px,3px) } }
      .pulse { animation: pulse ${ms(4)} ease-in-out infinite; transform-origin: ${markX}px ${markY}px; }
      @keyframes pulse { 0%,100% { opacity:${primitiveOpacity.chartGrid}; transform: scale(.94) } 50% { opacity:${primitiveOpacity.dividerLine}; transform: scale(1.06) } }
      .orbit { animation: orbit ${ms(8)} linear infinite; transform-origin: ${markX}px ${markY}px; }
      @keyframes orbit { to { transform: rotate(360deg) } }
      .sweep { animation: sweep ${ms(3)} ease-in-out infinite; }
      @keyframes sweep { 0% { transform: translateX(-280px) } 55%,100% { transform: translateX(330px) } }
      .hl { opacity: 0; animation: hl ${ms(5)} ease-in-out infinite; }
      .h2 { animation-delay: ${ms(0.75)} } .h3 { animation-delay: ${ms(1.5)} }
      .h4 { animation-delay: ${ms(2.25)} } .h5 { animation-delay: ${ms(3)} }
      @keyframes hl { 0%,100% { opacity:0 } 6%,12% { opacity:1 } 20% { opacity:0 } }
      .dash { stroke-dasharray: ${space[4]} ${space[6]}; animation: dash ${ms(1)} linear infinite; }
      @keyframes dash { to { stroke-dashoffset: -${space[20]} } }
      .bead { animation: bead ${ms(3)} cubic-bezier(.5,0,.5,1) infinite; }
      .bead2 { animation: bead ${ms(3)} cubic-bezier(.5,0,.5,1) infinite; animation-delay: ${ms(1.5)}; }
      @keyframes bead { 0% { transform: translateX(0); opacity:0 } 8% { opacity:1 } 92% { opacity:1 } 100% { transform: translateX(510px); opacity:0 } }
      @media (prefers-reduced-motion: reduce) {
        .halfL,.halfR,.pulse,.orbit,.sweep,.hl,.dash,.bead,.bead2 { animation: none }
      }
    </style>
  </defs>

  <rect x="${space[8]}" y="${space[8]}" width="624" height="184" rx="${radius.xl}" fill="url(#body)"/>
  <g clip-path="url(#bodyclip)" opacity="${primitiveOpacity.chartGrid}" stroke="${t.stroke}">
    <path d="M8 60H632M8 100H632M8 140H632"/>
    <path d="M88 8V192M168 8V192M248 8V192M328 8V192M408 8V192M488 8V192M568 8V192"/>
  </g>
  <rect x="${space[8]}" y="${space[8]}" width="624" height="184" rx="${radius.xl}" fill="none" stroke="${t.stroke}"/>

  <circle class="pulse" cx="${markX}" cy="${markY}" r="60" fill="url(#glow)"/>
  <g class="orbit">
    <circle cx="${markX}" cy="${markY - 58}" r="2.5" fill="${t.accent}"/>
    <circle cx="${markX}" cy="${markY + 58}" r="1.5" fill="${t.accentAlt}"/>
  </g>
  ${mark(markX, markY, t.mark)}

  <g mask="url(#wordmask)">
    <rect x="${textX - 10}" y="48" width="340" height="56" fill="${t.text}"/>
    <rect class="sweep" x="${textX - 10}" y="48" width="120" height="56" fill="url(#shine)"/>
  </g>

  <g font-family="${FAMILY}">
    <text x="${textX}" y="112" font-size="${size('sectionTitle')}" font-weight="${weight('sectionTitle')}" fill="${t.text}">Self-driving portfolio</text>
    <text x="${textX}" y="130" font-size="${size('caption')}" font-weight="${weight('caption')}" fill="${t.textMuted}">Money stays ready to use. The rest goes to work.</text>
    <g font-size="${size('fine')}" font-weight="${weight('fine')}">${chips
      .map((label, i) =>
        chip(textX + i * (chipW + chipGap), 146, chipW, label, t, i === 0 ? 'h1' : `h${i + 1}`),
      )
      .join('')}
    </g>
  </g>

  <g fill="none">
    <path d="M60 180H580" stroke="url(#rail)"/>
    <path class="dash" d="M60 180H580" stroke="${t.accent}" stroke-opacity="${primitiveOpacity.chartGrid}"/>
  </g>
  <g class="bead"><circle cx="60" cy="180" r="2" fill="${t.accent}"/></g>
  <g class="bead2"><circle cx="60" cy="180" r="1.5" fill="${t.accentAlt}"/></g>
</svg>
`;
}

function flow(t: Theme): string {
  const cardW = 150;
  const cardH = 84;
  const cardY = 64;
  const midY = cardY + cardH / 2;
  const leftX = space[20];
  const rightX = 640 - space[20] - cardW;
  const pad = primitiveSpace[18];

  const stateCard = (
    x: number,
    dot: string,
    title: string,
    sub: string,
    caption: string,
    barClass: string,
  ) => `
    <g>
      <rect x="${x}" y="${cardY}" width="${cardW}" height="${cardH}" rx="${radius.panel}" fill="${t.chip}" stroke="${t.stroke}"/>
      <circle cx="${x + pad}" cy="${cardY + pad}" r="3" fill="${dot}"/>
      <text x="${x + pad + space[10]}" y="${cardY + pad + 5}" font-size="${size('sectionTitle')}" font-weight="${weight('sectionTitle')}" fill="${t.text}">${title}</text>
      <text x="${x + pad}" y="${cardY + 40}" font-size="${size('footnote')}" font-weight="${weight('footnote')}" fill="${t.textMuted}">${sub}</text>
      <rect x="${x + pad}" y="${cardY + 50}" width="${cardW - pad * 2}" height="${space[6]}" rx="3" fill="${t.track}"/>
      <rect class="${barClass}" x="${x + pad}" y="${cardY + 50}" width="${cardW - pad * 2}" height="${space[6]}" rx="3" fill="url(#gauge)"/>
      <text x="${x + pad}" y="${cardY + 72}" font-size="${size('micro')}" font-weight="${weight('micro')}" fill="${t.textMuted}" letter-spacing="${primitiveType.tracking.walletId}">${caption}</text>
    </g>`;

  const inputs = ['risk', 'time horizon', 'liquidity need'];
  const inputW = 88;

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 236" width="1280" height="472"
     role="img" aria-label="Ready to use and Growing, connected by the on-chain allocation policy">
  <title>Ready to use ⇄ Growing</title>
  <desc>Generated by scripts/build-readme-assets.ts from @trinqa/tokens (${t.name} surface).</desc>
  <defs>
    <linearGradient id="body" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${t.bodyStart}"/><stop offset="100%" stop-color="${t.bodyEnd}"/>
    </linearGradient>
    <linearGradient id="gauge" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="${t.accent}"/><stop offset="100%" stop-color="${t.accentAlt}"/>
    </linearGradient>
    <style>
      .flowline { stroke-dasharray: ${space[4]} ${space[6]}; animation: flow ${ms(1)} linear infinite; }
      @keyframes flow { to { stroke-dashoffset: -${space[20]} } }
      .backline { stroke-dasharray: ${space[4]} ${space[6]}; animation: backflow ${ms(1.5)} linear infinite; }
      @keyframes backflow { to { stroke-dashoffset: ${space[20]} } }
      .beadA { offset-path: path("M${leftX + cardW} ${midY} H245"); animation: run ${ms(3)} linear infinite; }
      .beadB { offset-path: path("M395 ${midY} H${rightX}"); animation: run ${ms(3)} linear infinite; animation-delay: ${ms(0.5)}; }
      .beadC { offset-path: path("M545 148 V176 H95 V148"); animation: run ${ms(4)} linear infinite; animation-delay: ${ms(1)}; }
      @keyframes run { 0% { offset-distance: 0%; opacity: 0 } 10% { opacity:1 } 90% { opacity:1 } 100% { offset-distance: 100%; opacity: 0 } }
      .barReady { transform-origin: ${leftX + pad}px 0; animation: barReady ${ms(6)} ease-in-out infinite; }
      .barGrowing { transform-origin: ${rightX + pad}px 0; animation: barGrowing ${ms(6)} ease-in-out infinite; }
      @keyframes barReady { 0%,100% { transform: scaleX(.42) } 45%,55% { transform: scaleX(.78) } }
      @keyframes barGrowing { 0%,100% { transform: scaleX(.78) } 45%,55% { transform: scaleX(.42) } }
      .halo { animation: halo ${ms(3)} ease-in-out infinite; transform-origin: 320px ${midY}px; }
      @keyframes halo { 0%,100% { opacity:${primitiveOpacity.chartGrid} } 50% { opacity:${primitiveOpacity.dividerLine} } }
      .tick { animation: tick ${ms(4)} ease-in-out infinite; }
      .t2 { animation-delay: ${ms(1)} } .t3 { animation-delay: ${ms(2)} }
      @keyframes tick { 0%,100% { opacity:${primitiveOpacity.disabled} } 18%,26% { opacity:1 } }
      @media (prefers-reduced-motion: reduce) {
        .flowline,.backline,.beadA,.beadB,.beadC,.barReady,.barGrowing,.halo,.tick { animation: none }
      }
    </style>
  </defs>

  <rect x="${space[8]}" y="${space[8]}" width="624" height="220" rx="${radius.xl}" fill="url(#body)" stroke="${t.stroke}"/>

  <g font-family="${FAMILY}">
    <g font-size="${size('fine')}" font-weight="${weight('fine')}">${inputs
      .map(
        (label, i) =>
          `<g class="tick${i ? ` t${i + 1}` : ''}">${chip(176 + i * (inputW + space[12]), space[20], inputW, label, t)}</g>`,
      )
      .join('')}
    </g>
    <g stroke="${t.stroke}" fill="none">
      <path d="M220 44 C220 64 264 64 288 82"/>
      <path d="M320 44 V82"/>
      <path d="M420 44 C420 64 376 64 352 82"/>
    </g>

    <rect class="halo" x="241" y="80" width="158" height="52" rx="${radius.xl}" fill="none" stroke="${t.accent}"/>
    <rect x="245" y="84" width="${cardW}" height="44" rx="${radius.panel}" fill="${t.chip}" stroke="${t.stroke}"/>
    <text x="320" y="${midY - 3}" font-size="${size('label')}" font-weight="${weight('label')}" fill="${t.text}" text-anchor="middle">Allocation policy</text>
    <text x="320" y="${midY + 12}" font-size="${size('footnote')}" font-weight="${weight('footnote')}" fill="${t.textMuted}" text-anchor="middle">on-chain, user-signed</text>

    ${stateCard(leftX, t.accent, 'Ready to use', 'spendable right now', 'LIQUIDITY TARGET', 'barReady')}
    ${stateCard(rightX, t.accentAlt, 'Growing', 'eligible strategies', 'ALLOCATED', 'barGrowing')}

    <g fill="none" stroke="${t.accent}">
      <path class="flowline" d="M${leftX + cardW} ${midY} H245"/>
      <path class="flowline" d="M395 ${midY} H${rightX}"/>
    </g>
    <circle class="beadA" r="2.5" fill="${t.accent}"/>
    <circle class="beadB" r="2.5" fill="${t.accentAlt}"/>
    <g font-size="${size('micro')}" font-weight="${weight('micro')}" fill="${t.textMuted}" text-anchor="middle">
      <text x="207" y="${midY - 8}">put to work</text>
      <text x="432" y="${midY - 8}">allocate</text>
    </g>

    <path class="backline" d="M545 148 V176 H95 V148" fill="none" stroke="${t.accentAlt}"/>
    <circle class="beadC" r="2.5" fill="${t.accentAlt}"/>
    <text x="320" y="192" font-size="${size('caption')}" font-weight="${weight('caption')}" fill="${t.text}" text-anchor="middle">unwind only what the payment needs</text>
    <text x="320" y="214" font-size="${size('fine')}" font-weight="${weight('fine')}" fill="${t.textMuted}" text-anchor="middle">Stellar settlement · SEP-6/10/38 anchor · DeFindex vault · Soroswap route</text>
  </g>
</svg>
`;
}

const emit = (file: string, svg: string) => {
  if (svg.includes('undefined') || svg.includes('NaN')) {
    throw new Error(`${file}: a token lookup resolved to undefined/NaN`);
  }
  writeFileSync(resolve(outDir, file), svg);
  console.log(`wrote ${file}`);
};

mkdirSync(outDir, { recursive: true });
for (const theme of THEMES) {
  emit(`banner-${theme.name}.svg`, banner(theme));
  emit(`flow-${theme.name}.svg`, flow(theme));
}
