export const screenTokens = {
  wallet: {
    contentWidth: 366,
    headerToBalance: 15,
    balanceHeight: 192,
    balancePaddingTop: 22,
    balancePaddingHorizontal: 16,
    balanceTitleToValue: 7,
    balanceValueToMetrics: 12,
    metricLayerHeight: 66,
    detailsTopGap: 14,
    detailsHorizontalPadding: 16,
    detailsTopPadding: 22,
    titleToLimitCard: 18,
    limitCardHeight: 82,
    transactionTopGap: 14,
    transactionTitleToGroup: 18,
    transactionRowHeight: 56,
    transactionRowGap: 8,
  },
  progress: {
    contentWidth: 350,
    contentHorizontalOffset: 8,
    headlineTopGap: 22,
    chartTopGap: 11,
    metricTopGap: 21,
    metricGap: 7,
    lowerPanelTopGap: 18,
    lowerPanelWidth: 374,
    lowerPanelPadding: 16,
    pickerHeight: 44,
    pickerToRowsGap: 18,
  },
} as const;
