export const screenTokens = {
  wallet: {
    contentWidth: 366,
    headerToBalance: 15,
    balanceHeight: 192,
    balancePaddingTop: 22,
    balancePaddingHorizontal: 16,
    balanceTitleToValue: 7,
    balanceValueToMetrics: 12,
    metricLayerHeight: 66,
    detailsTopGap: 14,
    detailsHorizontalPadding: 16,
    detailsTopPadding: 22,
    titleToLimitCard: 18,
    limitCardHeight: 82,
    transactionTopGap: 14,
    transactionTitleToGroup: 18,
    transactionRowHeight: 56,
    transactionRowGap: 8,
  },
  earn: {
    contentWidth: 350,
    contentHorizontalOffset: 8,
    headlineTopGap: 22,
    chartTopGap: 11,
    metricTopGap: 21,
    metricGap: 7,
    lowerPanelTopGap: 18,
    lowerPanelWidth: 374,
    lowerPanelPadding: 16,
    pickerHeight: 44,
    pickerToRowsGap: 18,
  },
  activity: {
    contentWidth: 366,
    headerToTitle: 13,
    titleSubtitleGap: 4,
    subtitleToSegment: 6,
    segmentHeight: 44,
    segmentToPanel: 12,
    sectionGap: 14,
  },
  addMoney: {
    contentWidth: 366,
    sheetHeight: 374,
    headerToContent: 28,
    methodHeight: 44,
    amountTopGap: 30,
    amountFieldHeight: 62,
    quickAmountGap: 8,
    quickAmountHeight: 40,
    summaryTopGap: 18,
    summaryHeight: 120,
    cardPadding: 16,
    cardGap: 12,
    noticeHeight: 72,
    processingIconSize: 88,
    successIconSize: 92,
  },
  putToWork: {
    contentWidth: 366,
    headerToContent: 20,
    availableHeight: 64,
    strategyRowHeight: 62,
    strategyGap: 8,
    horizonTopGap: 18,
    horizonHeight: 44,
    explanationHeight: 48,
    summaryHeight: 120,
    cardPadding: 16,
    cardGap: 12,
  },
  paymentFlow: {
    contentWidth: 366,
    headerToContent: 20,
    recipientRowHeight: 64,
    recipientRowGap: 8,
    methodTopGap: 20,
    methodGap: 8,
    methodHeight: 76,
    currencyTopGap: 8,
    currencyHeight: 36,
    summaryHeight: 140,
    cardPadding: 16,
    cardGap: 12,
  },
  withdrawalFlow: {
    contentWidth: 366,
    summaryHeight: 158,
    destinationTopGap: 28,
    destinationRowGap: 8,
    destinationSectionGap: 20,
    sheetHeight: 340,
    fieldHeight: 48,
  },
} as const;
